import os
import shutil
import tempfile
import unittest
from decimal import Decimal

from pony.orm import *
from pony.orm import introspection
from pony.orm.tests import db_params, only_for, teardown_database


def _drop_schema(db, name):
    with db_session(ddl=True):
        db.execute("DROP SCHEMA IF EXISTS %s CASCADE" % name)


@only_for("postgres")
class TestIntrospection(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)
        self.dir = tempfile.mkdtemp()
        with db_session(ddl=True):
            rows = self.db.select(
                "SELECT tablename FROM pg_tables "
                "WHERE schemaname = current_schema()"
            )
            for tablename in rows:
                self.db.execute('DROP TABLE IF EXISTS "%s" CASCADE' % tablename)

    def tearDown(self):
        teardown_database(self.db)
        shutil.rmtree(self.dir)

    def _exec(self, sql):
        with db_session(ddl=True):
            self.db.execute(sql)

    def test_fill_basic_types(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (
                id serial PRIMARY KEY,
                name text NOT NULL,
                bio text,
                score numeric DEFAULT 0,
                tags text[],
                active boolean NOT NULL DEFAULT true
            )
            """
        )

        class Author(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Author.id, PrimaryKey)
        self.assertTrue(Author.id.auto)
        self.assertIsInstance(Author.name, Required)
        self.assertIsInstance(Author.bio, Optional)
        self.assertTrue(Author.bio.nullable)
        self.assertEqual(Author.score.py_type, Decimal)
        self.assertEqual(Author.score.sql_default, "0")
        self.assertEqual(Author.tags.py_type, StrArray)
        self.assertIsInstance(Author.active, Required)

        with db_session:
            Author(name="a", tags=["x", "y"], score=5)
        with db_session:
            a = Author[1]
            self.assertEqual(a.name, "a")
            self.assertEqual(list(a.tags), ["x", "y"])
            self.assertEqual(a.score, 5)
            self.assertEqual(a.active, True)

    def test_fill_identity_pk(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id integer GENERATED BY DEFAULT AS IDENTITY "
            "PRIMARY KEY, v text)"
        )

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.id.auto, "identity")
        with db_session:
            T(v="x")
        with db_session:
            self.assertEqual(T[1].v, "x")

    def test_fill_fk_relationship(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE book (
                id serial PRIMARY KEY,
                title text NOT NULL,
                author_id integer NOT NULL REFERENCES author(id)
            )
            """
        )

        class Author(db.Entity):
            pass

        class Book(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Book.author, Required)
        self.assertIs(Book.author.py_type, Author)
        self.assertIsInstance(Author.book_set, Set)
        self.assertIs(Author.book_set.reverse, Book.author)

        with db_session:
            a = Author(name="a")
            Book(title="t", author=a)
        with db_session:
            self.assertEqual([b.title for b in Author[1].book_set], ["t"])
            self.assertEqual(Book[1].author.name, "a")

    def test_declared_attrs_are_kept(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE book (
                id serial PRIMARY KEY,
                title text NOT NULL,
                author_id integer NOT NULL REFERENCES author(id)
            )
            """
        )

        class Author(db.Entity):
            pass

        class Book(db.Entity):
            title = Required(str, 100)
            author = Required(Author, column="author_id")

        db.introspect()
        self.assertIsInstance(Book.title, Required)
        self.assertEqual(Book.title.args, (100,))
        self.assertIs(Book.author.py_type, Author)
        self.assertEqual(Book.author.columns, ["author_id"])

    def test_declared_attr_missing_column_is_an_error(self):
        db = self.db
        self._exec("CREATE TABLE author (id serial PRIMARY KEY, name text)")

        class Author(db.Entity):
            nonexistent = Required(str)

        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_unique_index_and_default(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE t (
                id serial PRIMARY KEY,
                email text NOT NULL,
                status text DEFAULT 'new'
            );
            CREATE UNIQUE INDEX uq_t_email ON t (email);
            CREATE INDEX ix_t_status ON t (status)
            """
        )

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.email.is_unique, "uq_t_email")
        self.assertEqual(T.status.index, "ix_t_status")
        self.assertEqual(T.status.sql_default, "'new'")

    def test_dump_declarations(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE book (
                id serial PRIMARY KEY,
                title text NOT NULL,
                author_id integer NOT NULL REFERENCES author(id)
            )
            """
        )
        path = os.path.join(self.dir, "models.py")
        db.introspect(dump=path)
        with open(path) as f:
            result = f.read()
        self.assertIn("class Author(db.Entity):", result)
        self.assertIn("id = PrimaryKey(int, auto=True, name='author_pkey')", result)
        self.assertIn("name = Required(str)", result)
        self.assertIn("author = Required('Author', column='author_id', reverse='book_set')", result)
        self.assertIn("book_set = Set('Book', reverse='author')", result)
        self.assertIn("class Book(db.Entity):", result)
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect("NoSuchApp")
        # dump без объявленных классов пассивен: маппинг не строится
        self.assertEqual(db.schema, None)

    def test_referenced_entity_is_created(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE person (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE car (
                id serial PRIMARY KEY,
                make text NOT NULL,
                owner integer NOT NULL REFERENCES person(id)
            )
            """
        )

        class Person(db.Entity):
            cars1 = Set("Car")

        db.introspect()
        Car = db.entities["Car"]
        self.assertIs(Person.cars1.py_type, Car)
        self.assertIs(Person.cars1.reverse, Car.owner)
        self.assertIs(Car.owner.py_type, Person)
        self.assertEqual(sorted(a.name for a in Car._attrs_), ["id", "make", "owner"])

        with db_session:
            p = Person(name="Ann")
            Car(make="BMW", owner=p)
        with db_session:
            self.assertEqual([c.make for c in Person[1].cars1], ["BMW"])
            self.assertEqual(select(c.owner.name for c in Car)[:], ["Ann"])

    def test_referenced_entity_without_table_is_an_error(self):
        db = self.db
        self._exec("CREATE TABLE person (id serial PRIMARY KEY, name text)")

        class Person(db.Entity):
            cars1 = Set("Car")

        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_no_entities_is_an_error(self):
        db = self.db
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_second_introspect_is_an_error(self):
        db = self.db
        self._exec("CREATE TABLE t (id serial PRIMARY KEY, v text)")

        class T(db.Entity):
            pass

        db.introspect()
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_new_clones_without_models(self):
        db = self.db
        self._exec("CREATE TABLE tclear (id serial PRIMARY KEY, v text)")

        class TClear(db.Entity):
            pass

        db.introspect()
        self.assertIn("TClear", db.entities)

        new_db = db.new()
        self.assertEqual(new_db.entities, {})
        self.assertNotIn("TClear", new_db.__dict__)
        self.assertIsNone(new_db.schema)
        self.assertTrue(new_db._is_empty)
        # оригинал не тронут
        self.assertIn("TClear", db.entities)
        self.assertIsNotNone(db.schema)

        class TClone(new_db.Entity):
            _table_ = "tclear"

        with new_db:
            TClone(v="ok")
        with db_session:
            self.assertEqual([t.v for t in TClone.select()], ["ok"])
        new_db.disconnect()

    def test_new_then_lazy_introspection(self):
        db = self.db
        self._exec("CREATE TABLE tlazy (id serial PRIMARY KEY, v text)")
        new_db = db.new()

        class TLazy(new_db.Entity):
            _table_ = "tlazy"

        with new_db:
            TLazy(v="lazy")
        with db_session:
            self.assertEqual([t.v for t in TLazy.select()], ["lazy"])
        new_db.disconnect()

    def test_introspect_inside_plain_db_session(self):
        # интроспекции не нужна ddl-сессия
        db = self.db
        self._exec("CREATE TABLE tplain (id serial PRIMARY KEY, v text)")

        class TPlain(db.Entity):
            pass

        with db_session:
            db.introspect()
            TPlain(v="x")
        with db_session:
            self.assertEqual([t.v for t in TPlain.select()], ["x"])

    def test_introspect_application_schema(self):
        db = self.db
        _drop_schema(db, "intros")
        self._exec("CREATE SCHEMA intros")
        self._exec(
            "CREATE TABLE intros.person "
            "(id serial PRIMARY KEY, name text NOT NULL)"
        )
        self._exec(
            "CREATE TABLE intros.car "
            "(id serial PRIMARY KEY, make text NOT NULL, "
            "owner integer NOT NULL REFERENCES intros.person(id))"
        )
        self.addCleanup(_drop_schema, db, "intros")
        app = db.application("intros")

        class Person(app.Entity):
            cars1 = Set("Car")

        db.introspect()
        self.assertEqual(Person._table_, ("intros", "person"))
        car = db.Car
        self.assertIs(getattr(car, "_app_", None), app)
        self.assertEqual(car._table_, ("intros", "car"))
        with db_session:
            person = Person(name="ann")
            db.Car(make="bmw", owner=person)
        with db_session:
            self.assertEqual([p.name for p in Person.select()], ["ann"])
            self.assertEqual([c.make for c in db.Car.select()], ["bmw"])

    def test_dump_declarations_by_reference(self):
        db = self.db
        _drop_schema(db, "intros")
        self._exec("CREATE SCHEMA intros")
        self._exec(
            "CREATE TABLE intros.person "
            "(id serial PRIMARY KEY, name text NOT NULL)"
        )
        self._exec(
            "CREATE TABLE intros.car "
            "(id serial PRIMARY KEY, make text NOT NULL, "
            "owner integer NOT NULL REFERENCES intros.person(id))"
        )
        self.addCleanup(_drop_schema, db, "intros")
        app = db.application("intros")

        class Person(app.Entity):
            cars1 = Set("Car")

        # приложение можно передать строкой и объектом — дамп одинаковый
        path1 = os.path.join(self.dir, "m1.py")
        path2 = os.path.join(self.dir, "m2.py")
        db.introspect("intros", dump=path1)
        with open(path1) as f:
            by_name = f.read()
        db2 = db.new()

        class Person(db2.intros.Entity):
            cars1 = Set("Car")

        db2.introspect(db2.intros, dump=path2)
        with open(path2) as f:
            by_obj = f.read()
        self.assertEqual(by_name, by_obj)
        self.assertIn("class Person(db.Entity):", by_name)
        self.assertIn("cars1 = Set('Car', reverse='owner')", by_name)
        self.assertIn("_table_ = ('intros', 'person')", by_name)
        # файл + маппинг: после вызова схема построена
        self.assertIsNotNone(db.schema)
        db2.disconnect()

    def test_dump_declarations_uses_declared_attrs(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE person (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE car (
                id serial PRIMARY KEY,
                make text NOT NULL,
                owner_id integer NOT NULL REFERENCES person(id)
            )
            """
        )

        class Person(db.Entity):
            cars1 = Set("Car")

        class Car(db.Entity):
            renter = Required("Person", column="owner_id")

        path = os.path.join(self.dir, "models.py")
        db.introspect(dump=path)
        with open(path) as f:
            result = f.read()
        self.assertIn("cars1 = Set('Car', reverse='renter')", result)
        self.assertIn(
            "renter = Required('Person', column='owner_id', reverse='cars1')",
            result,
        )
        self.assertNotIn("car_set", result)
        self.assertIsNotNone(db.schema)

    def test_lazy_entity_access(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE person (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE car (
                id serial PRIMARY KEY,
                make text NOT NULL,
                owner_id integer NOT NULL REFERENCES person(id)
            )
            """
        )
        new_db = db.new()

        class Person(new_db.Entity):
            pass

        class Car(new_db.Entity):
            pass

        # вне with db: (и в глобальном db_session) интроспекция не запускается
        self.assertTrue(new_db._is_empty)
        with db_session:
            self.assertTrue(new_db._is_empty)
        # внутри with db: срабатывает ленивая интроспекция
        with new_db:
            person = new_db.Person(name="ann")
            new_db.Car(make="bmw", owner=person)
        with db_session:
            self.assertEqual([p.name for p in new_db.Person.select()], ["ann"])
            self.assertEqual([c.make for c in new_db.Car.select()], ["bmw"])
        new_db.disconnect()

    def test_introspect_scope_restricts_to_apps(self):
        db = self.db
        _drop_schema(db, "appone")
        _drop_schema(db, "apptwo")
        self._exec("CREATE SCHEMA appone")
        self._exec("CREATE SCHEMA apptwo")
        self._exec(
            "CREATE TABLE appone.thing (id serial PRIMARY KEY, v text)"
        )
        self._exec(
            "CREATE TABLE apptwo.other (id serial PRIMARY KEY, v text)"
        )
        self.addCleanup(_drop_schema, db, "appone")
        self.addCleanup(_drop_schema, db, "apptwo")
        app1 = db.application("appone")
        db.application("apptwo")

        class Thing(app1.Entity):
            pass

        # сущность чужого приложения в скоупе — ошибка
        db2 = db.new()

        class Thing2(db2.appone.Entity):
            pass

        class Other2(db2.apptwo.Entity):
            pass

        with self.assertRaises(introspection.IntrospectionError) as cm:
            db2.introspect("appone")
        self.assertIn("apptwo", str(cm.exception))
        db2.disconnect()

        # без чужих сущностей — интроспекция и дамп только своей схемы
        path = os.path.join(self.dir, "models.py")
        db.introspect("appone", dump=path)
        with open(path) as f:
            result = f.read()
        self.assertIn("class Thing(db.Entity):", result)
        self.assertIn("_table_ = ('appone', 'thing')", result)
        self.assertNotIn("class Other", result)

    def test_unique_registration_and_composite_indexes(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id serial PRIMARY KEY, email text NOT NULL, "
            "code text NOT NULL, region text NOT NULL)"
        )
        self._exec("CREATE UNIQUE INDEX uq_t_email ON t (email)")
        self._exec("CREATE UNIQUE INDEX uq_t_code_region ON t (code, region)")
        self._exec("CREATE INDEX ix_t_region_email ON t (region, email)")
        self._exec("CREATE UNIQUE INDEX uq_t_partial ON t (code) WHERE region = 'x'")
        self._exec("CREATE INDEX ix_t_expr ON t ((lower(email)))")

        class T(db.Entity):
            pass

        db.introspect()
        # unique= прошёл через конструктор: is_part_of_unique_index выставлен
        self.assertEqual(T.email.is_unique, "uq_t_email")
        self.assertTrue(T.email.is_part_of_unique_index)
        composite = {
            (i.name, tuple(a.name for a in i.attrs), i.is_unique)
            for i in T._indexes_
            if not i.is_pk
        }
        self.assertIn(("uq_t_code_region", ("code", "region"), True), composite)
        self.assertIn(("ix_t_region_email", ("region", "email"), False), composite)
        # частичный и выраженческий индексы не выводятся
        names = {i.name for i in T._indexes_}
        self.assertNotIn("uq_t_partial", names)
        self.assertNotIn("ix_t_expr", names)
        self.assertFalse(T.code.is_unique)

    def test_mixed_case_table(self):
        db = self.db
        self._exec('CREATE TABLE "MixedCase" (row_id serial PRIMARY KEY, v text)')

        class MixedCase(db.Entity):
            _table_ = "MixedCase"

        db.introspect()
        self.assertEqual([a.name for a in MixedCase._pk_attrs_], ["row_id"])
        self.assertIn("v", MixedCase._adict_)

    def test_default_cast_stripping(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id serial PRIMARY KEY, "
            "a text DEFAULT 'new'::text, "
            "b text DEFAULT ('x'::text || 'y'::text), "
            "c text DEFAULT upper('x'::text))"
        )

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.a.sql_default, "'new'")
        # каст внутри выражения — не трогаем
        self.assertEqual(T.b.sql_default, "('x'::text || 'y'::text)")
        self.assertEqual(T.c.sql_default, "upper('x'::text)")
    def test_unsupported_dialect_rejected(self):
        class FakeProvider:
            dialect = "Oracle"

        db = Database()
        db.provider = FakeProvider()
        with self.assertRaises(introspection.IntrospectionError):
            introspection.introspect(db)


@only_for("sqlite")
class TestIntrospectionSQLite(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        dbfile = os.path.join(self.tmp, "test.db")
        self.db = Database("sqlite", dbfile, create_db=True)

    def tearDown(self):
        teardown_database(self.db)
        shutil.rmtree(self.tmp)

    def _exec(self, sql):
        with db_session(ddl=True):
            self.db.execute(sql)

    def test_fill_basic_types(self):
        db = self.db
        self._exec(
            "CREATE TABLE author (id INTEGER PRIMARY KEY, name TEXT NOT NULL, "
            "bio TEXT, score INTEGER, active BOOLEAN NOT NULL DEFAULT 1)"
        )

        class Author(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Author.id, PrimaryKey)
        self.assertTrue(Author.id.auto)
        self.assertIsInstance(Author.name, Required)
        self.assertIsInstance(Author.bio, Optional)
        self.assertTrue(Author.bio.nullable)
        self.assertEqual(Author.score.py_type, int)
        self.assertEqual(Author.active.py_type, bool)
        with db_session:
            Author(name="a", score=5)
        with db_session:
            self.assertEqual(Author.select().first().name, "a")

    def test_fill_fk_relationship(self):
        db = self.db
        self._exec("CREATE TABLE author (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE book (id INTEGER PRIMARY KEY, title TEXT NOT NULL, "
            "author_id INTEGER NOT NULL REFERENCES author(id))"
        )

        class Author(db.Entity):
            pass

        class Book(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Book.author, Required)
        self.assertIs(Book.author.py_type, Author)
        self.assertIsInstance(Author.book_set, Set)
        with db_session:
            a = Author(name="a")
            Book(title="t", author=a)
        with db_session:
            self.assertEqual(Book.select().first().author.name, "a")

    def test_unique_index_and_default(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id INTEGER PRIMARY KEY, email TEXT NOT NULL, "
            "status TEXT DEFAULT 'new')"
        )
        self._exec("CREATE UNIQUE INDEX uq_t_email ON t (email)")
        self._exec("CREATE INDEX ix_t_status ON t (status)")

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.email.is_unique, "uq_t_email")
        self.assertEqual(T.status.index, "ix_t_status")
        self.assertEqual(T.status.sql_default, "'new'")

    def test_dump_declarations(self):
        db = self.db
        self._exec("CREATE TABLE author (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE book (id INTEGER PRIMARY KEY, title TEXT NOT NULL, "
            "author_id INTEGER NOT NULL REFERENCES author(id))"
        )

        path = os.path.join(self.tmp, "models.py")
        db.introspect(dump=path)
        with open(path) as f:
            result = f.read()
        self.assertIn("class Author(db.Entity):", result)
        self.assertIn("name = Required(str)", result)
        self.assertIn(
            "author = Required('Author', column='author_id', reverse='book_set')",
            result,
        )
        self.assertIn("book_set = Set('Book', reverse='author')", result)
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect("NoSuchApp")
        # dump без объявленных классов пассивен: маппинг не строится
        self.assertEqual(db.schema, None)

    def test_referenced_entity_is_created(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner INTEGER NOT NULL REFERENCES person(id))"
        )

        class Person(db.Entity):
            cars1 = Set("Car")

        db.introspect()
        Car = db.entities["Car"]
        self.assertIs(Person.cars1.py_type, Car)
        self.assertEqual(sorted(a.name for a in Car._attrs_), ["id", "make", "owner"])

    def test_introspect_inside_plain_db_session(self):
        # интроспекции не нужна ddl-сессия
        db = self.db
        self._exec("CREATE TABLE tplain (id INTEGER PRIMARY KEY, v TEXT)")

        class TPlain(db.Entity):
            pass

        with db_session:
            db.introspect()
            TPlain(v="x")
        with db_session:
            self.assertEqual([t.v for t in TPlain.select()], ["x"])

    def test_introspect_application(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner INTEGER NOT NULL REFERENCES person(id))"
        )
        app = db.application("intros")

        class Person(app.Entity):
            cars1 = Set("Car")

        db.introspect()
        self.assertIs(getattr(db.Car, "_app_", None), app)
        with db_session:
            person = Person(name="ann")
            db.Car(make="bmw", owner=person)
        with db_session:
            self.assertEqual([c.make for c in db.Car.select()], ["bmw"])

    def test_dump_declarations_by_reference(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner INTEGER NOT NULL REFERENCES person(id))"
        )
        app = db.application("intros")

        class Person(app.Entity):
            cars1 = Set("Car")

        # приложение можно передать строкой и объектом — дамп одинаковый
        path1 = os.path.join(self.tmp, "m1.py")
        path2 = os.path.join(self.tmp, "m2.py")
        db.introspect("intros", dump=path1)
        with open(path1) as f:
            by_name = f.read()
        db2 = db.new()

        class Person(db2.intros.Entity):
            cars1 = Set("Car")

        db2.introspect(db2.intros, dump=path2)
        with open(path2) as f:
            by_obj = f.read()
        self.assertEqual(by_name, by_obj)
        self.assertIn("cars1 = Set('Car', reverse='owner')", by_name)
        # файл + маппинг: после вызова схема построена
        self.assertIsNotNone(db.schema)
        db2.disconnect()

    def test_dump_declarations_uses_declared_attrs(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner_id INTEGER NOT NULL REFERENCES person(id))"
        )

        class Person(db.Entity):
            cars1 = Set("Car")

        class Car(db.Entity):
            renter = Required("Person", column="owner_id")

        path = os.path.join(self.tmp, "models.py")
        db.introspect(dump=path)
        with open(path) as f:
            result = f.read()
        self.assertIn("cars1 = Set('Car', reverse='renter')", result)
        self.assertIn(
            "renter = Required('Person', column='owner_id', reverse='cars1')",
            result,
        )
        self.assertNotIn("car_set", result)
        self.assertIsNotNone(db.schema)

    def test_lazy_entity_access(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner_id INTEGER NOT NULL REFERENCES person(id))"
        )
        new_db = db.new()

        class Person(new_db.Entity):
            pass

        class Car(new_db.Entity):
            pass

        # вне with db: (и в глобальном db_session) интроспекция не запускается
        self.assertTrue(new_db._is_empty)
        with db_session:
            self.assertTrue(new_db._is_empty)
        # внутри with db: срабатывает ленивая интроспекция
        with new_db:
            person = new_db.Person(name="ann")
            new_db.Car(make="bmw", owner=person)
        with db_session:
            self.assertEqual([p.name for p in new_db.Person.select()], ["ann"])
            self.assertEqual([c.make for c in new_db.Car.select()], ["bmw"])
        new_db.disconnect()

    def test_introspect_scope_restricts_to_apps(self):
        db = self.db
        self._exec("CREATE TABLE thing (id INTEGER PRIMARY KEY, v TEXT)")
        self._exec("CREATE TABLE other (id INTEGER PRIMARY KEY, v TEXT)")
        app1 = db.application("appone")
        db.application("apptwo")

        class Thing(app1.Entity):
            pass

        # сущность чужого приложения в скоупе — ошибка
        db2 = db.new()

        class Thing2(db2.appone.Entity):
            pass

        class Other2(db2.apptwo.Entity):
            pass

        with self.assertRaises(introspection.IntrospectionError) as cm:
            db2.introspect("appone")
        self.assertIn("apptwo", str(cm.exception))
        db2.disconnect()

        # MySQL/SQLite: таблицы приложения известны по его сущностям —
        # в дамп попадает только скоуп
        path = os.path.join(self.tmp, "models.py")
        db.introspect("appone", dump=path)
        with open(path) as f:
            result = f.read()
        self.assertIn("class Thing(db.Entity):", result)
        self.assertNotIn("class Other", result)

    def test_pk_column_not_named_id(self):
        # PK с именем, отличным от 'id', замещает неявный авто-id
        db = self.db
        self._exec(
            "CREATE TABLE person (person_id INTEGER PRIMARY KEY, name TEXT NOT NULL)"
        )
        self._exec("INSERT INTO person VALUES (7, 'alice')")

        class Person(db.Entity):
            pass

        db.introspect()
        self.assertEqual([a.name for a in Person._pk_attrs_], ["person_id"])
        self.assertIs(Person._pk_, Person.person_id)
        self.assertNotIn("id", Person._adict_)
        self.assertFalse(hasattr(Person, "id"))
        with db_session:
            self.assertEqual(Person[7].name, "alice")
            Person(name="bob")  # auto: rowid генерируется
        with db_session:
            self.assertEqual(Person.select().count(), 2)

    def test_composite_pk_guard(self):
        db = self.db
        self._exec(
            "CREATE TABLE pair (a INTEGER NOT NULL, b INTEGER NOT NULL, "
            "PRIMARY KEY (a, b))"
        )

        class Pair(db.Entity):
            pass

        with self.assertRaises(introspection.IntrospectionError) as cm:
            db.introspect()
        self.assertIn("Composite primary key", str(cm.exception))

    def test_table_without_pk_guard(self):
        db = self.db
        self._exec("CREATE TABLE nopk (x TEXT)")

        class Nopk(db.Entity):
            pass

        with self.assertRaises(introspection.IntrospectionError) as cm:
            db.introspect()
        self.assertIn("no primary key", str(cm.exception))

    def test_m2m_link_table_fill(self):
        # связочная таблица -> пара Set, entity для неё не создаётся
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec("CREATE TABLE tag (id INTEGER PRIMARY KEY, label TEXT)")
        self._exec(
            "CREATE TABLE person_tag ("
            "person_id INTEGER NOT NULL REFERENCES person(id), "
            "tag_id INTEGER NOT NULL REFERENCES tag(id), "
            "PRIMARY KEY (person_id, tag_id))"
        )

        class Person(db.Entity):
            pass

        class Tag(db.Entity):
            pass

        db.introspect()
        self.assertNotIn("PersonTag", db.entities)
        self.assertIs(Person.tag_set.py_type, Tag)
        self.assertIs(Tag.person_set.py_type, Person)
        self.assertEqual(Person.tag_set.table, "person_tag")
        with db_session:
            # разные id у сторон: перепутанные FK-колонки видны сразу
            p = Person(id=7, name="ann")
            t = Tag(id=3, label="x")
            t.person_set.add(p)
        with db_session:
            self.assertEqual([t.label for t in Person[7].tag_set], ["x"])
        with db_session:
            t2 = Tag(id=4, label="y")
            Person[7].tag_set.add(t2)
        with db_session:
            labels = sorted(t.label for t in Person[7].tag_set)
            self.assertEqual(labels, ["x", "y"])
            self.assertEqual(Tag[3].person_set.select().first().name, "ann")

    def test_m2m_link_table_with_extra_column_is_entity(self):
        # доп. колонка — уже не связочная: составной PK требует объявления
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec("CREATE TABLE tag (id INTEGER PRIMARY KEY, label TEXT)")
        self._exec(
            "CREATE TABLE person_tag ("
            "person_id INTEGER NOT NULL REFERENCES person(id), "
            "tag_id INTEGER NOT NULL REFERENCES tag(id), "
            "note TEXT, "
            "PRIMARY KEY (person_id, tag_id))"
        )

        class Person(db.Entity):
            pass

        class Tag(db.Entity):
            pass

        db.introspect()
        self.assertFalse(hasattr(Person, "tag_set"))

    def test_m2m_link_table_dump(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec("CREATE TABLE tag (id INTEGER PRIMARY KEY, label TEXT)")
        self._exec(
            "CREATE TABLE person_tag ("
            "person_id INTEGER NOT NULL REFERENCES person(id), "
            "tag_id INTEGER NOT NULL REFERENCES tag(id), "
            "PRIMARY KEY (person_id, tag_id))"
        )

        class Person(db.Entity):
            pass

        class Tag(db.Entity):
            pass

        path = os.path.join(self.tmp, "models.py")
        db.introspect(dump=path)
        with open(path) as f:
            result = f.read()
        self.assertNotIn("class PersonTag", result)
        self.assertNotIn("person_tag_set", result)
        self.assertIn(
            "tag_set = Set('Tag', table='person_tag', column='tag_id', "
            "reverse='person_set')",
            result,
        )
        self.assertIn(
            "person_set = Set('Person', column='person_id', reverse='tag_set')",
            result,
        )
        # дамп пастится: свежая база принимает его как декларации
        db2 = Database(
            "sqlite", os.path.join(self.tmp, "t2.db"), create_db=True
        )
        try:
            exec(result, {"db": db2})
            db2.generate_mapping(check_tables=False)
            self.assertEqual(
                db2.entities["Person"].tag_set.table, "person_tag"
            )
        finally:
            db2.disconnect()

    def test_dump_skips_sqlite_sequence(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, v TEXT)"
        )
        path = os.path.join(self.tmp, "models.py")
        db.introspect(dump=path)
        with open(path) as f:
            result = f.read()
        self.assertNotIn("SqliteSequence", result)
        self.assertNotIn("sqlite_sequence", result)

    def test_unique_registration_and_composite_indexes(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id INTEGER PRIMARY KEY, email TEXT NOT NULL, "
            "code TEXT NOT NULL, region TEXT NOT NULL)"
        )
        self._exec("CREATE UNIQUE INDEX uq_t_email ON t (email)")
        self._exec("CREATE UNIQUE INDEX uq_t_code_region ON t (code, region)")
        self._exec("CREATE INDEX ix_t_region_email ON t (region, email)")
        self._exec("CREATE UNIQUE INDEX uq_t_partial ON t (code) WHERE region = 'x'")
        self._exec("CREATE INDEX ix_t_expr ON t (lower(email))")

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.email.is_unique, "uq_t_email")
        self.assertTrue(T.email.is_part_of_unique_index)
        composite = {
            (i.name, tuple(a.name for a in i.attrs), i.is_unique)
            for i in T._indexes_
            if not i.is_pk
        }
        self.assertIn(("uq_t_code_region", ("code", "region"), True), composite)
        self.assertIn(("ix_t_region_email", ("region", "email"), False), composite)
        names = {i.name for i in T._indexes_}
        self.assertNotIn("uq_t_partial", names)
        self.assertNotIn("ix_t_expr", names)
        self.assertFalse(T.code.is_unique)
        # unique-индекс есть и в схеме БД (DDL-генерация миграций)
        schema_indexes = db.schema.tables[T._table_].indexes
        names = {getattr(i, "name", None) for i in schema_indexes.values()}
        self.assertIn("uq_t_email", names)

    def test_composite_indexes_in_dump(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id INTEGER PRIMARY KEY, code TEXT NOT NULL, "
            "region TEXT NOT NULL)"
        )
        self._exec("CREATE UNIQUE INDEX uq_t_code_region ON t (code, region)")
        self._exec("CREATE INDEX ix_t_region_code ON t (region, code)")

        class T(db.Entity):
            pass

        path = os.path.join(self.tmp, "models.py")
        db.introspect(dump=path)
        with open(path) as f:
            result = f.read()
        self.assertIn("unique(code, region, name='uq_t_code_region')", result)
        self.assertIn(
            "composite_index(region, code, name='ix_t_region_code')", result
        )
        # дамп пастится
        db2 = Database("sqlite", os.path.join(self.tmp, "t2.db"), create_db=True)
        try:
            exec(result, {"db": db2})
            db2.generate_mapping(check_tables=False)
        finally:
            db2.disconnect()

    def test_fk_column_index_and_default(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, "
            "owner_id INTEGER NOT NULL DEFAULT 1 REFERENCES person(id))"
        )
        self._exec("CREATE INDEX ix_car_owner ON car (owner_id)")

        class Person(db.Entity):
            pass

        class Car(db.Entity):
            pass

        db.introspect()
        self.assertEqual(Car.owner.index, "ix_car_owner")
        self.assertEqual(Car.owner.sql_default, "1")

        # в дампе FK-атрибут тоже несёт index/sql_default
        path = os.path.join(self.tmp, "models.py")
        db2 = self.db.new()
        try:
            class Person(db2.Entity):
                pass

            class Car(db2.Entity):
                pass

            db2.introspect(dump=path)
            with open(path) as f:
                result = f.read()
            self.assertIn(
                "owner = Required('Person', column='owner_id', "
                "sql_default='1', index='ix_car_owner', reverse='car_set')",
                result,
            )
        finally:
            db2.disconnect()

    def test_entity_name_preserves_mixed_case(self):
        db = self.db
        self._exec("CREATE TABLE mixedCase (id INTEGER PRIMARY KEY, v TEXT)")
        path = os.path.join(self.tmp, "models.py")
        db.introspect(dump=path)
        with open(path) as f:
            result = f.read()
        self.assertIn("class MixedCase(db.Entity):", result)

    def test_sqlite_composite_pk_order_in_dump(self):
        db = self.db
        self._exec(
            "CREATE TABLE pair (a INTEGER NOT NULL, b INTEGER NOT NULL, "
            "PRIMARY KEY (b, a))"
        )
        path = os.path.join(self.tmp, "models.py")
        db.introspect(dump=path)
        with open(path) as f:
            result = f.read()
        # порядок колонок ключа, а не таблицы; без шумного name=None
        self.assertIn("PrimaryKey(b, a)", result)
        self.assertNotIn("name=None", result)

    def test_declared_contract_checks_type_and_nullability(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id INTEGER PRIMARY KEY, name TEXT NOT NULL, "
            "note TEXT, score INTEGER)"
        )

        class T(db.Entity):
            name = Required(int)  # поверх TEXT — несовпадение типа

        with self.assertRaises(introspection.IntrospectionError) as cm:
            db.introspect()
        self.assertIn("type int", str(cm.exception))

        db2 = self.db.new()

        class T2(db2.Entity):
            _table_ = "t"
            name = Optional(str)  # поверх NOT NULL

        with self.assertRaises(introspection.IntrospectionError) as cm:
            db2.introspect()
        self.assertIn("NOT NULL", str(cm.exception))
        db2.disconnect()

        db3 = self.db.new()

        class T3(db3.Entity):
            _table_ = "t"
            note = Required(str)  # поверх nullable

        with self.assertRaises(introspection.IntrospectionError) as cm:
            db3.introspect()
        self.assertIn("nullable", str(cm.exception))
        db3.disconnect()

        # кастомный python-тип контрактом не проверяется (нельзя вычислить)
        class Money:
            pass

        attr = Required(Money)
        attr._init_(T, "score")
        introspection._check_declared_matches_schema(
            db,
            attr,
            "score",
            {"type": "INTEGER", "typtype": None, "notnull": True},
        )  # тип не проверяется, nullability совпадает — не падает

    def test_failed_introspection_rolls_back(self):
        db = self.db
        self._exec("CREATE TABLE t1 (id INTEGER PRIMARY KEY, a TEXT)")
        self._exec("CREATE TABLE t2 (id INTEGER PRIMARY KEY, b TEXT)")

        class T1(db.Entity):
            pass

        class T2(db.Entity):
            wrong = Required(str, column="no_such_column")

        before = {
            name: list(entity._new_attrs_)
            for name, entity in db.entities.items()
        }
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()
        # откат: флаг вернулся, атрибуты не остались наполовину добавленными
        self.assertTrue(db._is_empty)
        self.assertIsNone(db.schema)
        for name, entity in db.entities.items():
            self.assertEqual(
                [a.name for a in entity._new_attrs_],
                [a.name for a in before[name]],
            )
        # повторная попытка — та же понятная ошибка, а не «name already in use»
        with self.assertRaises(introspection.IntrospectionError) as cm:
            db.introspect()
        self.assertIn("no_such_column", str(cm.exception))

    def test_async_with_db_lazy_introspection(self):
        # async with db: — триггер ленивой интроспекции (решение 14);
        # интроспекция sync и выполняется до входа в async-контекст
        import asyncio

        db = self.db
        self._exec("CREATE TABLE person (person_id INTEGER PRIMARY KEY, name TEXT)")
        new_db = db.new()

        class Person(new_db.Entity):
            pass

        async def go():
            async with new_db:
                return [a.name for a in new_db.entities["Person"]._pk_attrs_]

        self.assertEqual(asyncio.run(go()), ["person_id"])
        new_db.disconnect()


if __name__ == "__main__":
    unittest.main()
