import unittest

from pony.orm import *
from pony.orm.tests import db_params, only_for, teardown_database
from pony.orm.tests.testutils import *


class TestIdentityOption(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)

    def tearDown(self):
        teardown_database(self.db)

    def test_invalid_value(self):
        db = self.db

        with self.assertRaises(TypeError):
            class Bad(db.Entity):
                id = PrimaryKey(int, auto="bogus")

    def test_postgres_only(self):
        db = self.db
        if db.provider.dialect == "PostgreSQL":
            self.skipTest('auto="identity" is allowed on PostgreSQL')

        with self.assertRaises(TypeError):
            class Bad(db.Entity):
                id = PrimaryKey(int, auto="identity")
            db.generate_mapping()


class TestCommentsOption(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)

    def tearDown(self):
        teardown_database(self.db)

    def test_ignored_outside_postgres(self):
        db = self.db
        if db.provider.dialect == "PostgreSQL":
            self.skipTest("COMMENT ON is emitted on PostgreSQL")

        class Person(db.Entity):
            """A comment."""

            name = Required(str, doc="Full name")

        db.generate_mapping(create_tables=True)
        script = db.schema.generate_create_script()
        self.assertNotIn("COMMENT", script)

    def test_invalid_doc(self):
        db = self.db

        with self.assertRaises(TypeError):
            class Bad(db.Entity):
                name = Required(str, doc=123)


@only_for("PostgreSQL")
class TestIdentityAndCommentsPostgreSQL(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)

    def tearDown(self):
        teardown_database(self.db)

    def test_identity(self):
        db = self.db

        class Person(db.Entity):
            id = PrimaryKey(int, auto="identity")

        db.generate_mapping(create_tables=True)
        script = db.schema.generate_create_script()
        self.assertIn(
            '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', script
        )
        with db_session:
            p = Person()
            self.assertIsNotNone(p.id)
            p2 = Person(id=42)
            self.assertEqual(p2.id, 42)

    def test_comments(self):
        db = self.db

        class Person(db.Entity):
            """People and their profiles."""

            name = Required(str, doc="Full name")

        db.generate_mapping(create_tables=True)
        script = db.schema.generate_create_script()
        self.assertIn(
            "COMMENT ON TABLE \"person\" IS 'People and their profiles.'", script
        )
        self.assertIn(
            "COMMENT ON COLUMN \"person\".\"name\" IS 'Full name'", script
        )


if __name__ == "__main__":
    unittest.main()
