import os
import shutil
import tempfile
import unittest
from decimal import Decimal

from pony.orm import *
from pony.orm import introspection
from pony.orm.tests import db_params, only_for, teardown_database


def _drop_schema(db, name):
    with db_session(ddl=True):
        db.execute("DROP SCHEMA IF EXISTS %s CASCADE" % name)


@only_for("postgres")
class TestIntrospection(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)
        with db_session(ddl=True):
            rows = self.db.select(
                "SELECT tablename FROM pg_tables "
                "WHERE schemaname = current_schema()"
            )
            for tablename in rows:
                self.db.execute('DROP TABLE IF EXISTS "%s" CASCADE' % tablename)

    def tearDown(self):
        teardown_database(self.db)

    def _exec(self, sql):
        with db_session(ddl=True):
            self.db.execute(sql)

    def test_fill_basic_types(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (
                id serial PRIMARY KEY,
                name text NOT NULL,
                bio text,
                score numeric DEFAULT 0,
                tags text[],
                active boolean NOT NULL DEFAULT true
            )
            """
        )

        class Author(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Author.id, PrimaryKey)
        self.assertTrue(Author.id.auto)
        self.assertIsInstance(Author.name, Required)
        self.assertIsInstance(Author.bio, Optional)
        self.assertTrue(Author.bio.nullable)
        self.assertEqual(Author.score.py_type, Decimal)
        self.assertEqual(Author.score.sql_default, "0")
        self.assertEqual(Author.tags.py_type, StrArray)
        self.assertIsInstance(Author.active, Required)

        with db_session:
            Author(name="a", tags=["x", "y"], score=5)
        with db_session:
            a = Author[1]
            self.assertEqual(a.name, "a")
            self.assertEqual(list(a.tags), ["x", "y"])
            self.assertEqual(a.score, 5)
            self.assertEqual(a.active, True)

    def test_fill_identity_pk(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id integer GENERATED BY DEFAULT AS IDENTITY "
            "PRIMARY KEY, v text)"
        )

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.id.auto, "identity")
        with db_session:
            T(v="x")
        with db_session:
            self.assertEqual(T[1].v, "x")

    def test_fill_fk_relationship(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE book (
                id serial PRIMARY KEY,
                title text NOT NULL,
                author_id integer NOT NULL REFERENCES author(id)
            )
            """
        )

        class Author(db.Entity):
            pass

        class Book(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Book.author, Required)
        self.assertIs(Book.author.py_type, Author)
        self.assertIsInstance(Author.book_set, Set)
        self.assertIs(Author.book_set.reverse, Book.author)

        with db_session:
            a = Author(name="a")
            Book(title="t", author=a)
        with db_session:
            self.assertEqual([b.title for b in Author[1].book_set], ["t"])
            self.assertEqual(Book[1].author.name, "a")

    def test_declared_attrs_are_kept(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE book (
                id serial PRIMARY KEY,
                title text NOT NULL,
                author_id integer NOT NULL REFERENCES author(id)
            )
            """
        )

        class Author(db.Entity):
            pass

        class Book(db.Entity):
            title = Required(str, 100)
            author = Required(Author, column="author_id")

        db.introspect()
        self.assertIsInstance(Book.title, Required)
        self.assertEqual(Book.title.args, (100,))
        self.assertIs(Book.author.py_type, Author)
        self.assertEqual(Book.author.columns, ["author_id"])

    def test_declared_attr_missing_column_is_an_error(self):
        db = self.db
        self._exec("CREATE TABLE author (id serial PRIMARY KEY, name text)")

        class Author(db.Entity):
            nonexistent = Required(str)

        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_unique_index_and_default(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE t (
                id serial PRIMARY KEY,
                email text NOT NULL,
                status text DEFAULT 'new'
            );
            CREATE UNIQUE INDEX uq_t_email ON t (email);
            CREATE INDEX ix_t_status ON t (status)
            """
        )

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.email.is_unique, "uq_t_email")
        self.assertEqual(T.status.index, "ix_t_status")
        self.assertEqual(T.status.sql_default, "'new'")

    def test_dump_declarations(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE book (
                id serial PRIMARY KEY,
                title text NOT NULL,
                author_id integer NOT NULL REFERENCES author(id)
            )
            """
        )
        result = db.introspect("Author", "Book")
        self.assertIsInstance(result, str)
        # красивый repr: в консоли/ноутбуке видно код, а не repr строки
        self.assertEqual(repr(result), str(result))
        self.assertIn("class Author(db.Entity):", result)
        self.assertIn("id = PrimaryKey(int, auto=True, name='author_pkey')", result)
        self.assertIn("name = Required(str)", result)
        self.assertIn("author = Required('Author', column='author_id', reverse='book_set')", result)
        self.assertIn("book_set = Set('Book', reverse='author')", result)
        self.assertIn("class Book(db.Entity):", result)
        # отбор только указанных сущностей
        only_book = db.introspect("book")
        self.assertIn("class Book(db.Entity):", only_book)
        self.assertNotIn("class Author(db.Entity):", only_book)
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect("NoSuchEntity")
        # dump-режим не трогает классы
        self.assertEqual(db.schema, None)

    def test_referenced_entity_is_created(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE person (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE car (
                id serial PRIMARY KEY,
                make text NOT NULL,
                owner integer NOT NULL REFERENCES person(id)
            )
            """
        )

        class Person(db.Entity):
            cars1 = Set("Car")

        db.introspect()
        Car = db.entities["Car"]
        self.assertIs(Person.cars1.py_type, Car)
        self.assertIs(Person.cars1.reverse, Car.owner)
        self.assertIs(Car.owner.py_type, Person)
        self.assertEqual(sorted(a.name for a in Car._attrs_), ["id", "make", "owner"])

        with db_session:
            p = Person(name="Ann")
            Car(make="BMW", owner=p)
        with db_session:
            self.assertEqual([c.make for c in Person[1].cars1], ["BMW"])
            self.assertEqual(select(c.owner.name for c in Car)[:], ["Ann"])

    def test_referenced_entity_without_table_is_an_error(self):
        db = self.db
        self._exec("CREATE TABLE person (id serial PRIMARY KEY, name text)")

        class Person(db.Entity):
            cars1 = Set("Car")

        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_no_entities_is_an_error(self):
        db = self.db
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_second_introspect_is_an_error(self):
        db = self.db
        self._exec("CREATE TABLE t (id serial PRIMARY KEY, v text)")

        class T(db.Entity):
            pass

        db.introspect()
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_new_clones_without_models(self):
        db = self.db
        self._exec("CREATE TABLE tclear (id serial PRIMARY KEY, v text)")

        class TClear(db.Entity):
            pass

        db.introspect()
        self.assertIn("TClear", db.entities)

        new_db = db.new()
        self.assertEqual(new_db.entities, {})
        self.assertNotIn("TClear", new_db.__dict__)
        self.assertIsNone(new_db.schema)
        self.assertTrue(new_db._is_empty)
        # оригинал не тронут
        self.assertIn("TClear", db.entities)
        self.assertIsNotNone(db.schema)

        class TClone(new_db.Entity):
            _table_ = "tclear"

        with new_db:
            TClone(v="ok")
        with db_session:
            self.assertEqual([t.v for t in TClone.select()], ["ok"])
        new_db.disconnect()

    def test_new_then_lazy_introspection(self):
        db = self.db
        self._exec("CREATE TABLE tlazy (id serial PRIMARY KEY, v text)")
        new_db = db.new()

        class TLazy(new_db.Entity):
            _table_ = "tlazy"

        with new_db:
            TLazy(v="lazy")
        with db_session:
            self.assertEqual([t.v for t in TLazy.select()], ["lazy"])
        new_db.disconnect()

    def test_introspect_inside_plain_db_session(self):
        # интроспекции не нужна ddl-сессия
        db = self.db
        self._exec("CREATE TABLE tplain (id serial PRIMARY KEY, v text)")

        class TPlain(db.Entity):
            pass

        with db_session:
            db.introspect()
            TPlain(v="x")
        with db_session:
            self.assertEqual([t.v for t in TPlain.select()], ["x"])

    def test_introspect_application_schema(self):
        db = self.db
        _drop_schema(db, "intros")
        self._exec("CREATE SCHEMA intros")
        self._exec(
            "CREATE TABLE intros.person "
            "(id serial PRIMARY KEY, name text NOT NULL)"
        )
        self._exec(
            "CREATE TABLE intros.car "
            "(id serial PRIMARY KEY, make text NOT NULL, "
            "owner integer NOT NULL REFERENCES intros.person(id))"
        )
        self.addCleanup(_drop_schema, db, "intros")
        app = db.application("intros")

        class Person(app.Entity):
            cars1 = Set("Car")

        db.introspect()
        self.assertEqual(Person._table_, ("intros", "person"))
        car = db.Car
        self.assertIs(getattr(car, "_app_", None), app)
        self.assertEqual(car._table_, ("intros", "car"))
        with db_session:
            person = Person(name="ann")
            db.Car(make="bmw", owner=person)
        with db_session:
            self.assertEqual([p.name for p in Person.select()], ["ann"])
            self.assertEqual([c.make for c in db.Car.select()], ["bmw"])

    def test_dump_declarations_by_reference(self):
        db = self.db
        _drop_schema(db, "intros")
        self._exec("CREATE SCHEMA intros")
        self._exec(
            "CREATE TABLE intros.person "
            "(id serial PRIMARY KEY, name text NOT NULL)"
        )
        self._exec(
            "CREATE TABLE intros.car "
            "(id serial PRIMARY KEY, make text NOT NULL, "
            "owner integer NOT NULL REFERENCES intros.person(id))"
        )
        self.addCleanup(_drop_schema, db, "intros")
        app = db.application("intros")

        class Person(app.Entity):
            cars1 = Set("Car")

        by_name = db.introspect("Person")
        by_qualified = db.introspect("intros.Person")
        by_class = db.introspect(app.Person)
        self.assertEqual(str(by_name), str(by_class))
        self.assertEqual(str(by_qualified), str(by_class))
        self.assertIn("class Person(db.Entity):", by_class)
        self.assertIn("cars1 = Set('Car', reverse='owner')", by_class)
        self.assertIn("_table_ = ('intros', 'person')", by_class)
        self.assertIsNone(db.schema)

    def test_dump_declarations_uses_declared_attrs(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE person (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE car (
                id serial PRIMARY KEY,
                make text NOT NULL,
                owner_id integer NOT NULL REFERENCES person(id)
            )
            """
        )

        class Person(db.Entity):
            cars1 = Set("Car")

        class Car(db.Entity):
            renter = Required("Person", column="owner_id")

        result = db.introspect("Person", "Car")
        self.assertIn("cars1 = Set('Car', reverse='renter')", result)
        self.assertIn(
            "renter = Required('Person', column='owner_id', reverse='cars1')",
            result,
        )
        self.assertNotIn("car_set", result)
        self.assertEqual(db.schema, None)

    def test_lazy_entity_access_after_named_dump(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE person (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE car (
                id serial PRIMARY KEY,
                make text NOT NULL,
                owner_id integer NOT NULL REFERENCES person(id)
            )
            """
        )
        new_db = db.new()
        new_db.introspect("Person", "Car")
        # дамп пассивный: ни классов, ни маппинга, ленивый режим вооружён
        self.assertIsNone(new_db.schema)
        self.assertTrue(new_db._is_empty)
        self.assertNotIn("Person", new_db.__dict__)
        # вне with db: (и в глобальном db_session) доступа к db.Person нет
        with self.assertRaises(AttributeError):
            new_db.Person
        with db_session:
            with self.assertRaises(AttributeError):
                new_db.Person
        # внутри with db: срабатывает ленивая интроспекция
        with new_db:
            person = new_db.Person(name="ann")
            new_db.Car(make="bmw", owner=person)
        with db_session:
            self.assertEqual([p.name for p in new_db.Person.select()], ["ann"])
            self.assertEqual([c.make for c in new_db.Car.select()], ["bmw"])
        new_db.disconnect()


class TestIntrospectionDialectGuard(unittest.TestCase):
    def test_unsupported_dialect_rejected(self):
        class FakeProvider:
            dialect = "Oracle"

        db = Database()
        db.provider = FakeProvider()
        with self.assertRaises(introspection.IntrospectionError):
            introspection.introspect(db)


@only_for("sqlite")
class TestIntrospectionSQLite(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        dbfile = os.path.join(self.tmp, "test.db")
        self.db = Database("sqlite", dbfile, create_db=True)

    def tearDown(self):
        teardown_database(self.db)
        shutil.rmtree(self.tmp)

    def _exec(self, sql):
        with db_session(ddl=True):
            self.db.execute(sql)

    def test_fill_basic_types(self):
        db = self.db
        self._exec(
            "CREATE TABLE author (id INTEGER PRIMARY KEY, name TEXT NOT NULL, "
            "bio TEXT, score INTEGER, active BOOLEAN NOT NULL DEFAULT 1)"
        )

        class Author(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Author.id, PrimaryKey)
        self.assertTrue(Author.id.auto)
        self.assertIsInstance(Author.name, Required)
        self.assertIsInstance(Author.bio, Optional)
        self.assertTrue(Author.bio.nullable)
        self.assertEqual(Author.score.py_type, int)
        self.assertEqual(Author.active.py_type, bool)
        with db_session:
            Author(name="a", score=5)
        with db_session:
            self.assertEqual(Author.select().first().name, "a")

    def test_fill_fk_relationship(self):
        db = self.db
        self._exec("CREATE TABLE author (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE book (id INTEGER PRIMARY KEY, title TEXT NOT NULL, "
            "author_id INTEGER NOT NULL REFERENCES author(id))"
        )

        class Author(db.Entity):
            pass

        class Book(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Book.author, Required)
        self.assertIs(Book.author.py_type, Author)
        self.assertIsInstance(Author.book_set, Set)
        with db_session:
            a = Author(name="a")
            Book(title="t", author=a)
        with db_session:
            self.assertEqual(Book.select().first().author.name, "a")

    def test_unique_index_and_default(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id INTEGER PRIMARY KEY, email TEXT NOT NULL, "
            "status TEXT DEFAULT 'new')"
        )
        self._exec("CREATE UNIQUE INDEX uq_t_email ON t (email)")
        self._exec("CREATE INDEX ix_t_status ON t (status)")

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.email.is_unique, "uq_t_email")
        self.assertEqual(T.status.index, "ix_t_status")
        self.assertEqual(T.status.sql_default, "'new'")

    def test_dump_declarations(self):
        db = self.db
        self._exec("CREATE TABLE author (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE book (id INTEGER PRIMARY KEY, title TEXT NOT NULL, "
            "author_id INTEGER NOT NULL REFERENCES author(id))"
        )

        result = db.introspect("Author", "Book")
        # красивый repr: в консоли/ноутбуке видно код, а не repr строки
        self.assertEqual(repr(result), str(result))
        self.assertIn("class Author(db.Entity):", result)
        self.assertIn("name = Required(str)", result)
        self.assertIn(
            "author = Required('Author', column='author_id', reverse='book_set')",
            result,
        )
        self.assertIn("book_set = Set('Book', reverse='author')", result)
        # отбор только указанных сущностей
        only_book = db.introspect("book")
        self.assertIn("class Book(db.Entity):", only_book)
        self.assertNotIn("class Author(db.Entity):", only_book)
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect("NoSuchEntity")
        self.assertEqual(db.schema, None)

    def test_referenced_entity_is_created(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner INTEGER NOT NULL REFERENCES person(id))"
        )

        class Person(db.Entity):
            cars1 = Set("Car")

        db.introspect()
        Car = db.entities["Car"]
        self.assertIs(Person.cars1.py_type, Car)
        self.assertEqual(sorted(a.name for a in Car._attrs_), ["id", "make", "owner"])

    def test_introspect_inside_plain_db_session(self):
        # интроспекции не нужна ddl-сессия
        db = self.db
        self._exec("CREATE TABLE tplain (id INTEGER PRIMARY KEY, v TEXT)")

        class TPlain(db.Entity):
            pass

        with db_session:
            db.introspect()
            TPlain(v="x")
        with db_session:
            self.assertEqual([t.v for t in TPlain.select()], ["x"])

    def test_introspect_application(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner INTEGER NOT NULL REFERENCES person(id))"
        )
        app = db.application("intros")

        class Person(app.Entity):
            cars1 = Set("Car")

        db.introspect()
        self.assertIs(getattr(db.Car, "_app_", None), app)
        with db_session:
            person = Person(name="ann")
            db.Car(make="bmw", owner=person)
        with db_session:
            self.assertEqual([c.make for c in db.Car.select()], ["bmw"])

    def test_dump_declarations_by_reference(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner INTEGER NOT NULL REFERENCES person(id))"
        )
        app = db.application("intros")

        class Person(app.Entity):
            cars1 = Set("Car")

        by_name = db.introspect("Person")
        by_qualified = db.introspect("intros.Person")
        by_class = db.introspect(app.Person)
        self.assertEqual(str(by_name), str(by_class))
        self.assertEqual(str(by_qualified), str(by_class))
        self.assertIn("cars1 = Set('Car', reverse='owner')", by_class)
        self.assertIsNone(db.schema)

    def test_dump_declarations_uses_declared_attrs(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner_id INTEGER NOT NULL REFERENCES person(id))"
        )

        class Person(db.Entity):
            cars1 = Set("Car")

        class Car(db.Entity):
            renter = Required("Person", column="owner_id")

        result = db.introspect("Person", "Car")
        self.assertIn("cars1 = Set('Car', reverse='renter')", result)
        self.assertIn(
            "renter = Required('Person', column='owner_id', reverse='cars1')",
            result,
        )
        self.assertNotIn("car_set", result)
        self.assertEqual(db.schema, None)

    def test_lazy_entity_access_after_named_dump(self):
        db = self.db
        self._exec("CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")
        self._exec(
            "CREATE TABLE car (id INTEGER PRIMARY KEY, make TEXT NOT NULL, "
            "owner_id INTEGER NOT NULL REFERENCES person(id))"
        )
        new_db = db.new()
        new_db.introspect("Person", "Car")
        # дамп пассивный: ни классов, ни маппинга, ленивый режим вооружён
        self.assertIsNone(new_db.schema)
        self.assertTrue(new_db._is_empty)
        self.assertNotIn("Person", new_db.__dict__)
        # вне with db: (и в глобальном db_session) доступа к db.Person нет
        with self.assertRaises(AttributeError):
            new_db.Person
        with db_session:
            with self.assertRaises(AttributeError):
                new_db.Person
        # внутри with db: срабатывает ленивая интроспекция
        with new_db:
            person = new_db.Person(name="ann")
            new_db.Car(make="bmw", owner=person)
        with db_session:
            self.assertEqual([p.name for p in new_db.Person.select()], ["ann"])
            self.assertEqual([c.make for c in new_db.Car.select()], ["bmw"])
        new_db.disconnect()


if __name__ == "__main__":
    unittest.main()
