import os
import shutil
import tempfile
import unittest
from decimal import Decimal

from pony.orm import *
from pony.orm import introspection
from pony.orm.tests import db_params, only_for, teardown_database


@only_for("postgres")
class TestIntrospection(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)
        with db_session(ddl=True):
            rows = self.db.select(
                "SELECT tablename FROM pg_tables "
                "WHERE schemaname = current_schema()"
            )
            for tablename in rows:
                self.db.execute('DROP TABLE IF EXISTS "%s" CASCADE' % tablename)

    def tearDown(self):
        teardown_database(self.db)

    def _exec(self, sql):
        with db_session(ddl=True):
            self.db.execute(sql)

    def test_fill_basic_types(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (
                id serial PRIMARY KEY,
                name text NOT NULL,
                bio text,
                score numeric DEFAULT 0,
                tags text[],
                active boolean NOT NULL DEFAULT true
            )
            """
        )

        class Author(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Author.id, PrimaryKey)
        self.assertTrue(Author.id.auto)
        self.assertIsInstance(Author.name, Required)
        self.assertIsInstance(Author.bio, Optional)
        self.assertTrue(Author.bio.nullable)
        self.assertEqual(Author.score.py_type, Decimal)
        self.assertEqual(Author.score.sql_default, "0")
        self.assertEqual(Author.tags.py_type, StrArray)
        self.assertIsInstance(Author.active, Required)

        with db_session:
            Author(name="a", tags=["x", "y"], score=5)
        with db_session:
            a = Author[1]
            self.assertEqual(a.name, "a")
            self.assertEqual(list(a.tags), ["x", "y"])
            self.assertEqual(a.score, 5)
            self.assertEqual(a.active, True)

    def test_fill_identity_pk(self):
        db = self.db
        self._exec(
            "CREATE TABLE t (id integer GENERATED BY DEFAULT AS IDENTITY "
            "PRIMARY KEY, v text)"
        )

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.id.auto, "identity")
        with db_session:
            T(v="x")
        with db_session:
            self.assertEqual(T[1].v, "x")

    def test_fill_fk_relationship(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE book (
                id serial PRIMARY KEY,
                title text NOT NULL,
                author_id integer NOT NULL REFERENCES author(id)
            )
            """
        )

        class Author(db.Entity):
            pass

        class Book(db.Entity):
            pass

        db.introspect()
        self.assertIsInstance(Book.author, Required)
        self.assertIs(Book.author.py_type, Author)
        self.assertIsInstance(Author.book_set, Set)
        self.assertIs(Author.book_set.reverse, Book.author)

        with db_session:
            a = Author(name="a")
            Book(title="t", author=a)
        with db_session:
            self.assertEqual([b.title for b in Author[1].book_set], ["t"])
            self.assertEqual(Book[1].author.name, "a")

    def test_declared_attrs_are_kept(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE book (
                id serial PRIMARY KEY,
                title text NOT NULL,
                author_id integer NOT NULL REFERENCES author(id)
            )
            """
        )

        class Author(db.Entity):
            pass

        class Book(db.Entity):
            title = Required(str, 100)
            author = Required(Author, column="author_id")

        db.introspect()
        self.assertIsInstance(Book.title, Required)
        self.assertEqual(Book.title.args, (100,))
        self.assertIs(Book.author.py_type, Author)
        self.assertEqual(Book.author.columns, ["author_id"])

    def test_declared_attr_missing_column_is_an_error(self):
        db = self.db
        self._exec("CREATE TABLE author (id serial PRIMARY KEY, name text)")

        class Author(db.Entity):
            nonexistent = Required(str)

        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_unique_index_and_default(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE t (
                id serial PRIMARY KEY,
                email text NOT NULL,
                status text DEFAULT 'new'
            );
            CREATE UNIQUE INDEX uq_t_email ON t (email);
            CREATE INDEX ix_t_status ON t (status)
            """
        )

        class T(db.Entity):
            pass

        db.introspect()
        self.assertEqual(T.email.is_unique, "uq_t_email")
        self.assertEqual(T.status.index, "ix_t_status")
        self.assertEqual(T.status.sql_default, "'new'")

    def test_dump_declarations(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE author (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE book (
                id serial PRIMARY KEY,
                title text NOT NULL,
                author_id integer NOT NULL REFERENCES author(id)
            )
            """
        )
        directory = tempfile.mkdtemp()
        try:
            out = os.path.join(directory, "entities.py")
            result = db.introspect(out=out)
            self.assertEqual(result, out)
            with open(out) as f:
                content = f.read()
            self.assertIn("class Author(db.Entity):", content)
            self.assertIn("id = PrimaryKey(int, auto=True, name='author_pkey')", content)
            self.assertIn("name = Required(str)", content)
            self.assertIn("author = Required('Author', column='author_id', reverse='book_set')", content)
            self.assertIn("book_set = Set('Book', reverse='author')", content)
            self.assertIn("class Book(db.Entity):", content)
            # dump-режим не трогает классы
            self.assertEqual(db.schema, None)
        finally:
            shutil.rmtree(directory)

    def test_referenced_entity_is_created(self):
        db = self.db
        self._exec(
            """
            CREATE TABLE person (id serial PRIMARY KEY, name text NOT NULL);
            CREATE TABLE car (
                id serial PRIMARY KEY,
                make text NOT NULL,
                owner integer NOT NULL REFERENCES person(id)
            )
            """
        )

        class Person(db.Entity):
            cars1 = Set("Car")

        db.introspect()
        Car = db.entities["Car"]
        self.assertIs(Person.cars1.py_type, Car)
        self.assertIs(Person.cars1.reverse, Car.owner)
        self.assertIs(Car.owner.py_type, Person)
        self.assertEqual(sorted(a.name for a in Car._attrs_), ["id", "make", "owner"])

        with db_session:
            p = Person(name="Ann")
            Car(make="BMW", owner=p)
        with db_session:
            self.assertEqual([c.make for c in Person[1].cars1], ["BMW"])
            self.assertEqual(select(c.owner.name for c in Car)[:], ["Ann"])

    def test_referenced_entity_without_table_is_an_error(self):
        db = self.db
        self._exec("CREATE TABLE person (id serial PRIMARY KEY, name text)")

        class Person(db.Entity):
            cars1 = Set("Car")

        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_no_entities_is_an_error(self):
        db = self.db
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()

    def test_second_introspect_is_an_error(self):
        db = self.db
        self._exec("CREATE TABLE t (id serial PRIMARY KEY, v text)")

        class T(db.Entity):
            pass

        db.introspect()
        with self.assertRaises(introspection.IntrospectionError):
            db.introspect()


class TestIntrospectionNotSupported(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)

    def tearDown(self):
        teardown_database(self.db)

    def test_non_postgres_rejected(self):
        if self.db.provider.dialect == "PostgreSQL":
            self.skipTest("introspection is supported on PostgreSQL")
        with self.assertRaises(introspection.IntrospectionError):
            self.db.introspect()


if __name__ == "__main__":
    unittest.main()
