import unittest

from pony.orm import *
from pony.orm.dbschema import DBComment
from pony.orm.tests import db_params, only_for, teardown_database
from pony.orm.tests.testutils import *


class TestIdentityOption(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)

    def tearDown(self):
        teardown_database(self.db)

    def test_invalid_value(self):
        db = self.db

        with self.assertRaises(TypeError):
            class Bad(db.Entity):
                id = PrimaryKey(int, auto="bogus")

    def test_postgres_only(self):
        db = self.db
        if db.provider.dialect == "PostgreSQL":
            self.skipTest('auto="identity" is allowed on PostgreSQL')

        with self.assertRaises(TypeError):
            class Bad(db.Entity):
                id = PrimaryKey(int, auto="identity")
            db.generate_mapping()


class TestCommentsOption(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)

    def tearDown(self):
        teardown_database(self.db)

    def test_ignored_outside_postgres(self):
        db = self.db
        if db.provider.dialect == "PostgreSQL":
            self.skipTest("COMMENT ON is emitted on PostgreSQL")

        class Person(db.Entity):
            """A comment."""

            name = Required(str, comment="Full name")

        db.generate_mapping(create_tables=True)
        script = db.schema.generate_create_script()
        self.assertNotIn("COMMENT", script)

    def test_invalid_comment(self):
        db = self.db

        with self.assertRaises(TypeError):
            class Bad(db.Entity):
                name = Required(str, comment=123)

    def test_comment_object_contract(self):
        # create_tables requires every object from get_objects_to_create()
        # to expose name, typename and exists() — DBComment must comply
        db = self.db
        db.provider.dialect = "PostgreSQL"

        class Note(db.Entity):
            """A note."""

            body = Optional(str, comment="Body text")

        db.generate_mapping(check_tables=False, create_tables=False)
        table = db.schema.tables[Note._table_]
        comments = [
            obj
            for obj in table.get_objects_to_create()
            if isinstance(obj, DBComment)
        ]
        self.assertEqual(len(comments), 2)
        for comment in comments:
            self.assertTrue(db.provider.base_name(comment.name))
            self.assertIsNone(comment.exists(db.provider, None))
            self.assertIn("COMMENT ON", comment.get_create_command())


@only_for("postgres")
class TestIdentityAndCommentsPostgreSQL(unittest.TestCase):
    def setUp(self):
        self.db = Database(**db_params)

    def tearDown(self):
        teardown_database(self.db)

    def test_identity(self):
        db = self.db

        class Person(db.Entity):
            id = PrimaryKey(int, auto="identity")

        db.generate_mapping(create_tables=True)
        script = db.schema.generate_create_script()
        self.assertIn(
            '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', script
        )
        with db_session:
            p = Person()
        self.assertIsNotNone(p.id)
        with db_session:
            p2 = Person(id=42)
            self.assertEqual(p2.id, 42)

    def test_comments(self):
        db = self.db

        class Person(db.Entity):
            """People and their profiles."""

            name = Required(str, comment="Full name")

        db.generate_mapping(create_tables=True)
        script = db.schema.generate_create_script()
        self.assertIn(
            "COMMENT ON TABLE \"person\" IS 'People and their profiles.'", script
        )
        self.assertIn(
            "COMMENT ON COLUMN \"person\".\"name\" IS 'Full name'", script
        )


if __name__ == "__main__":
    unittest.main()
